/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Test service. Represents a row in the &quot;Test_Test&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.example.test.model.impl.TestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.example.test.model.impl.TestImpl</code>.
 * </p>
 *
 * @author Gerard Bartalot
 * @see Test
 * @generated
 */
@ProviderType
public interface TestModel extends BaseModel<Test>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test model instance should use the {@link Test} interface instead.
	 */

	/**
	 * Returns the primary key of this test.
	 *
	 * @return the primary key of this test
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test.
	 *
	 * @param primaryKey the primary key of this test
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the test ID of this test.
	 *
	 * @return the test ID of this test
	 */
	public long getTestId();

	/**
	 * Sets the test ID of this test.
	 *
	 * @param testId the test ID of this test
	 */
	public void setTestId(long testId);

	/**
	 * Returns the name of this test.
	 *
	 * @return the name of this test
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this test.
	 *
	 * @param name the name of this test
	 */
	public void setName(String name);

	/**
	 * Returns the description of this test.
	 *
	 * @return the description of this test
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this test.
	 *
	 * @param description the description of this test
	 */
	public void setDescription(String description);

	/**
	 * Returns the test date of this test.
	 *
	 * @return the test date of this test
	 */
	public Date getTestDate();

	/**
	 * Sets the test date of this test.
	 *
	 * @param testDate the test date of this test
	 */
	public void setTestDate(Date testDate);

	/**
	 * Returns the status of this test.
	 *
	 * @return the status of this test
	 */
	public Integer getStatus();

	/**
	 * Sets the status of this test.
	 *
	 * @param status the status of this test
	 */
	public void setStatus(Integer status);

	/**
	 * Returns the company ID of this test.
	 *
	 * @return the company ID of this test
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this test.
	 *
	 * @param companyId the company ID of this test
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this test.
	 *
	 * @return the group ID of this test
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this test.
	 *
	 * @param groupId the group ID of this test
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this test.
	 *
	 * @return the user ID of this test
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this test.
	 *
	 * @param userId the user ID of this test
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this test.
	 *
	 * @return the user uuid of this test
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this test.
	 *
	 * @param userUuid the user uuid of this test
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this test.
	 *
	 * @return the user name of this test
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this test.
	 *
	 * @param userName the user name of this test
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this test.
	 *
	 * @return the create date of this test
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this test.
	 *
	 * @param createDate the create date of this test
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this test.
	 *
	 * @return the modified date of this test
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this test.
	 *
	 * @param modifiedDate the modified date of this test
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the priority of this test.
	 *
	 * @return the priority of this test
	 */
	public Integer getPriority();

	/**
	 * Sets the priority of this test.
	 *
	 * @param priority the priority of this test
	 */
	public void setPriority(Integer priority);

	/**
	 * Returns the due date of this test.
	 *
	 * @return the due date of this test
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this test.
	 *
	 * @param dueDate the due date of this test
	 */
	public void setDueDate(Date dueDate);

	@Override
	public Test cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}